apiVersion: v1
kind: Service
metadata:
  name: my-frontend-clusterip

spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000

  selector:
    app: facebook-frontend
    type: frontend
