apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-deployment
  labels:
    app: my-api
    type: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-api
      type: backend
  template:
    metadata:
      name: my-api-deployment
      labels:
        app: my-api
        type: backend
    spec:
      containers:
        - name: my-api-container
          image: fdobkowski/api_image
          imagePullPolicy: Never

          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-postgres-secret
                  key: PG_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: POSTGRES_DATABASE
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-postgres-config
                  key: POSTGRES_PORT

      restartPolicy: Always