apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-postgres-pv
  labels:
    type: local
    app: my-postgres

spec:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/run/desktop/mnt/host/c/users/florian/Desktop/Projects/React/facebook_clone/k8s/postgres/data'
