apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-postgres-pvc
  labels:
    app: my-postgres

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi